# Generated by Django 5.0.14 on 2026-02-19 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_options_user_unique_manager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCertificateApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('approved_on', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_certificates', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_approvals', to='api.member')),
            ],
            options={
                'ordering': ['-year', '-approved_on'],
                'unique_together': {('member', 'year')},
            },
        ),
    ]
