# Generated by Django 5.0.14 on 2026-02-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SAVING_REMINDER', 'Saving Reminder'), ('LOAN_REMINDER', 'Loan Reminder'), ('SYSTEM', 'System')], max_length=30),
        ),
    ]
