# Generated by Django 5.0.14 on 2026-02-28 07:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_employee_external_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometric',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.biometric_photo_upload_to),
        ),
    ]
