REPORT_TEXT = {
    "rw": {
        "company.name": "IKIMINA REHOBOTH",
        "company.subtitle": "Raporo ya Sisitemu y'Ubuyobozi",
        "company.location": "Kigali - Rwanda",
        "company.registration": "Reg. No 1213-T-00009",
        "company.address": "Remera sector- Gasabo District",
        "company.email_line": "email: ikiminarehoboth@gmail.com",
        "company.phone_line": "Tel: +250788305423 / +250788551596",
        "company.bank_line": "BK ACC NO: 0004 2069 5448 375",
        "meta.generated_by": "Byakozwe na",
        "meta.generated_at": "Byasohowe ku",
        "meta.page": "Urupapuro",
        "meta.signature": "Umukono",
        "meta.name": "Amazina",
        "meta.title": "Umutwe",
        "meta.date": "Itariki",
        "meta.contact": "Telefone",
        "meta.email": "Imeli",
        "report.loans.title": "Raporo y'Inguzanyo",
        "report.loans.subtitle": "Raporo y'inguzanyo zishingiye kuri nyirazo, ubwoko, amafaranga n'imimerere",
        "report.loan_repayments.title": "Raporo y'Imyishyurire y'Inguzanyo",
        "report.loan_repayments.subtitle": "Amateka y'ubwishyu bw'inguzanyo harimo igice cy'umwenda fatizo n'inyungu",
        "report.fines.title": "Raporo y'Ibihano",
        "report.fines.subtitle": "Ibihano byanditswe ku munyamuryango, itegeko, amafaranga n'imimerere yabyo",
        "report.monthly_savings.title": "Raporo y'Ubwizigame bwa buri kwezi",
        "report.monthly_savings.subtitle": "Raporo y'ikusanywa ry'ubwizigame harimo amande n'imimerere y'ubwishyu",
        "report.member_savings_statement.title": "Statement y'Ubwizigame bw'Umunyamuryango",
        "report.member_savings_statement.subtitle": "Amateka y'ubwizigame bwawe agaragaza amafaranga yinjiye n'ibyarangiye kuri konti",
        "report.annual_closing.title": "Raporo y'Isoza ry'Umwaka",
        "report.annual_closing.subtitle": "Incamake y'isoza ry'imari rya buri mwaka",
        "report.profit_payouts.title": "Raporo y'Ubwishyu bw'Inyungu z'Abanyamuryango",
        "report.profit_payouts.subtitle": "Amateka y'ubwishyu bw'inyungu z'abanyamuryango bwanditswe",
        "report.profit_requests.title": "Raporo y'Ibyifuzo by'Inyungu",
        "report.profit_requests.subtitle": "Ibyifuzo by'inyungu z'abanyamuryango n'imimerere y'isuzuma",
        "report.transaction_logs.title": "Raporo y'Amateka y'Ibikorwa",
        "report.transaction_logs.subtitle": "Raporo y'isuzuma ry'ibikorwa yashunguwe",
        "report.income.title": "Raporo y'Injiza",
        "report.income.subtitle": "Amateka y'injiza zose zanditswe muri sisitemu",
        "report.expenses.title": "Raporo y'Ibyakoreshejwe",
        "report.expenses.subtitle": "Amateka y'ibyishyuwe n'ibyakoreshejwe byanditswe",
        "report.membership_fees.title": "Raporo y'Amafaranga y'Ubunyamuryango",
        "report.membership_fees.subtitle": "Amateka y'amafaranga y'ubunyamuryango yakiriwe",
        "report.salary_payments.title": "Raporo y'Imishahara",
        "report.salary_payments.subtitle": "Amateka y'ubwishyu bw'imishahara bwanditswe",
        "report.loan_requests.title": "Raporo y'Ibyifuzo by'Inguzanyo",
        "report.loan_requests.subtitle": "Ibyifuzo by'inguzanyo byakiriwe n'imimerere yabyo",
        "report.member_certificate.title": "Icyemezo cy'Umunyamuryango",
        "report.member_certificate.subtitle": "Icyemezo cy'umunyamuryango cyemejwe n'ikimina",
        "label.id": "ID",
        "label.owner": "Nyirabyo",
        "label.owner_type": "Ubwoko bwa nyira",
        "label.loan_type": "Ubwoko bw'inguzanyo",
        "label.principal": "Amafaranga fatizo",
        "label.total_amount": "Amafaranga yose",
        "label.remaining": "Asigaye",
        "label.remaining_balance": "Asigaye kwishyura",
        "label.status": "Imimerere",
        "label.due_date": "Itariki ntarengwa",
        "label.loan_id": "ID y'inguzanyo",
        "label.member": "Umunyamuryango",
        "label.rule": "Itegeko",
        "label.type": "Ubwoko",
        "label.amount": "Amafaranga",
        "label.interest": "Inyungu",
        "label.calculated_on": "Yabazwe ku",
        "label.category": "Icyiciro",
        "label.month": "Ukwezi",
        "label.year": "Umwaka",
        "label.saved_on": "Yabitswe ku",
        "label.received_by": "Byakiriwe na",
        "label.late_fine": "Amande yo gukererwa",
        "label.savings": "Ubwizigame",
        "label.total_adjusted_capital": "Umutungo rusange ubazweho",
        "label.profit_rate": "Ikigero cy'inyungu",
        "label.loan_interest": "Inyungu z'inguzanyo",
        "label.fines": "Ibihano",
        "label.expenses": "Ibyakoreshejwe",
        "label.net_profit": "Inyungu nyakuri",
        "label.closed_by": "Byafunzwe na",
        "label.closed_on": "Byafunzwe ku",
        "label.paid_on": "Yishyuwe ku",
        "label.recorded_by": "Byanditswe na",
        "label.notes": "Ibisobanuro",
        "label.requested_by": "Wasabye",
        "label.mode": "Uburyo",
        "label.requested": "Byasabwe",
        "label.approved": "Byemejwe",
        "label.requested_on": "Byasabwe ku",
        "label.reviewed_by": "Byasuzumwe na",
        "label.time": "Igihe",
        "label.user": "Ukoresha",
        "label.action": "Igikorwa",
        "label.model": "Model",
        "label.object_id": "ID y'ikintu",
        "label.details": "Ibisobanuro",
        "label.value": "Agaciro",
        "label.ip_address": "IP Address",
        "label.search": "Shakisha",
        "label.status_group": "Itsinda ry'imimerere",
        "label.owner_id": "ID ya nyira",
        "label.loan_status": "Imimerere y'inguzanyo",
        "label.due_from": "Itariki ntarengwa kuva",
        "label.due_to": "Itariki ntarengwa kugeza",
        "label.from": "Kuva",
        "label.to": "Kugeza",
        "label.member_id": "ID y'umunyamuryango",
        "label.is_paid": "Ryishyuwe",
        "label.total_records": "Umubare w'inyandiko",
        "label.total_principal": "Amafaranga fatizo yose",
        "label.total_paid": "Amafaranga yose yishyuwe",
        "label.principal_repaid": "Amafaranga fatizo yishyuwe",
        "label.interest_income": "Inyungu zinjiye",
        "label.paid_fines": "Ibihano byishyuwe",
        "label.waived_fines": "Ibihano byavanyweho",
        "label.total_savings": "Ubwizigame bwose",
        "label.total_late_fines": "Amande yose yo gukererwa",
        "label.total_closings": "Umubare w'amasoza",
        "label.total_expenses": "Ibyakoreshejwe byose",
        "label.total_payouts": "Umubare w'ubwishyu",
        "label.total_requests": "Umubare w'ibyifuzo",
        "label.pending_requests": "Ibyifuzo bitegereje",
        "label.requested_amount": "Amafaranga yasabwe",
        "label.approved_amount": "Amafaranga yemejwe",
        "label.employee": "Umukozi",
        "label.department": "Ishami",
        "label.national_id": "Indangamuntu",
        "label.account_number": "Numero ya konti",
        "label.reference": "Reference",
        "label.balance": "Balance",
        "label.opening_balance": "Balance yatangiranye",
        "label.closing_balance": "Balance isoje",
        "label.statement_period": "Igihe cya statement",
        "label.payment_status": "Imimerere y'ubwishyu",
        "label.approved_loan": "Inguzanyo yemejwe",
        "label.authorized_by": "Byemejwe na",
        "label.approved_on": "Byemejwe ku",
        "label.issued_date": "Byasohowe ku",
        "label.joined_date": "Yinjiye ku",
        "label.year_savings": "Ubwizigame bwo muri uwo mwaka",
        "label.year_profit": "Inyungu z'uwo mwaka",
        "label.lifetime_savings": "Ubwizigame bwose",
        "label.lifetime_profit": "Inyungu zose",
        "label.lifetime_total": "Igiteranyo cyose",
        "value.member": "Umunyamuryango",
        "value.client": "Umukiliya",
        "value.paid": "Yishyuwe",
        "value.unpaid": "Ntirishyurwa",
        "value.ongoing": "Irakomeje",
        "value.defaulted": "Yakererewe bikabije",
        "value.pending": "Bitegereje",
        "value.approved": "Byemejwe",
        "value.rejected": "Byanzwe",
        "value.waived": "Byavanyweho",
        "value.late": "Byakererewe",
        "value.on_time": "Ku gihe",
        "value.overdue": "Byarenze igihe",
        "value.near_due": "Bigiye kugera igihe",
        "value.committee_review_required": "Bisaba isuzuma rya komite",
        "value.all_profits": "Inyungu zose",
        "value.partial_profit": "Igice cy'inyungu",
        "value.self_requested": "Yisabiye",
        "value.requested_on_behalf": "Yasabiwe",
        "value.direct_entry": "Yanditswe direct",
        "value.fine_type_saving": "Amande yo gukererwa kwizigama",
        "value.fine_type_loan": "Amande yo gukererwa kwishyura inguzanyo",
        "value.fine_type_admin": "Ubuyobozi",
        "value.fine_type_other": "Ibindi",
        "value.transaction_saving": "Ubwizigame",
        "value.transaction_loan": "Inguzanyo",
        "value.transaction_repayment": "Kwishyura inguzanyo",
        "value.transaction_fine": "Igihano",
        "value.transaction_expense": "Icyakoreshejwe",
        "value.transaction_membership": "Amafaranga y'ubunyamuryango",
        "value.transaction_system": "Sisitemu",
        "value.action_create": "Kurema",
        "value.action_update": "Guhindura",
        "value.action_delete": "Gusiba",
        "value.action_pay": "Kwishyura",
        "value.role_admin": "Admin",
        "value.role_manager": "Manager",
        "value.role_member": "Umunyamuryango",
        "value.role_teller": "Teller",
        "value.role_loan_officer": "Umukozi ushinzwe inguzanyo",
        "value.role_finance": "Umukozi w'imari",
        "value.role_auditor": "Umugenzuzi",
        "value.role_client": "Umukiliya",
        "value.role_staff": "Umukozi",
        "value.all_time": "Ibihe byose",
    },
    "en": {
        "company.name": "IKIMINA REHOBOTH",
        "company.subtitle": "Management System Report",
        "company.location": "Kigali - Rwanda",
        "company.registration": "Reg. No 1213-T-00009",
        "company.address": "Remera sector- Gasabo District",
        "company.email_line": "email: ikiminarehoboth@gmail.com",
        "company.phone_line": "Tel: +250788305423 / +250788551596",
        "company.bank_line": "BK ACC NO: 0004 2069 5448 375",
        "meta.generated_by": "Generated by",
        "meta.generated_at": "Generated at",
        "meta.page": "Page",
        "meta.signature": "Signature",
        "meta.name": "Name",
        "meta.title": "Title",
        "meta.date": "Date",
        "meta.contact": "Contact",
        "meta.email": "Email",
        "report.loans.title": "Loans Report",
        "report.loans.subtitle": "Loans by owner, type, amount and status",
        "report.loan_repayments.title": "Loan Repayments Report",
        "report.loan_repayments.subtitle": "Repayment history with principal and interest breakdown",
        "report.fines.title": "Fines Report",
        "report.fines.subtitle": "Fine records by member, rule, amount and status",
        "report.monthly_savings.title": "Monthly Savings Report",
        "report.monthly_savings.subtitle": "Savings collection report with fines and payment status",
        "report.member_savings_statement.title": "Member Savings Statement",
        "report.member_savings_statement.subtitle": "Statement of your savings deposits with running account balance",
        "report.annual_closing.title": "Annual Closing Report",
        "report.annual_closing.subtitle": "Annual financial closing summary by year",
        "report.profit_payouts.title": "Member Profit Payouts Report",
        "report.profit_payouts.subtitle": "Recorded member profit payouts",
        "report.profit_requests.title": "Profit Requests Report",
        "report.profit_requests.subtitle": "Member profit requests and review status",
        "report.transaction_logs.title": "Transaction Logs Report",
        "report.transaction_logs.subtitle": "Filtered operational audit report",
        "report.income.title": "Income Report",
        "report.income.subtitle": "Recorded income entries across the system",
        "report.expenses.title": "Expenses Report",
        "report.expenses.subtitle": "Recorded expense entries and disbursements",
        "report.membership_fees.title": "Membership Fees Report",
        "report.membership_fees.subtitle": "Recorded membership fee payments",
        "report.salary_payments.title": "Salary Payments Report",
        "report.salary_payments.subtitle": "Recorded employee salary payments",
        "report.loan_requests.title": "Loan Requests Report",
        "report.loan_requests.subtitle": "Submitted loan requests and review outcomes",
        "report.member_certificate.title": "Member Certificate",
        "report.member_certificate.subtitle": "Approved membership certificate",
        "label.id": "ID",
        "label.owner": "Owner",
        "label.owner_type": "Owner Type",
        "label.loan_type": "Loan Type",
        "label.principal": "Principal",
        "label.total_amount": "Total Amount",
        "label.remaining": "Remaining",
        "label.remaining_balance": "Remaining Balance",
        "label.status": "Status",
        "label.due_date": "Due Date",
        "label.loan_id": "Loan ID",
        "label.member": "Member",
        "label.rule": "Rule",
        "label.type": "Type",
        "label.amount": "Amount",
        "label.interest": "Interest",
        "label.calculated_on": "Calculated On",
        "label.category": "Category",
        "label.month": "Month",
        "label.year": "Year",
        "label.saved_on": "Saved On",
        "label.received_by": "Received By",
        "label.late_fine": "Late Fine",
        "label.savings": "Savings",
        "label.total_adjusted_capital": "Total adjusted capital",
        "label.profit_rate": "Profit rate",
        "label.loan_interest": "Loan Interest",
        "label.fines": "Fines",
        "label.expenses": "Expenses",
        "label.net_profit": "Net Profit",
        "label.closed_by": "Closed By",
        "label.closed_on": "Closed On",
        "label.paid_on": "Paid On",
        "label.recorded_by": "Recorded By",
        "label.notes": "Notes",
        "label.requested_by": "Requested By",
        "label.mode": "Mode",
        "label.requested": "Requested",
        "label.approved": "Approved",
        "label.requested_on": "Requested On",
        "label.reviewed_by": "Reviewed By",
        "label.time": "Time",
        "label.user": "User",
        "label.action": "Action",
        "label.model": "Model",
        "label.object_id": "Object ID",
        "label.details": "Details",
        "label.value": "Value",
        "label.ip_address": "IP Address",
        "label.search": "Search",
        "label.status_group": "Status Group",
        "label.owner_id": "Owner ID",
        "label.loan_status": "Loan Status",
        "label.due_from": "Due From",
        "label.due_to": "Due To",
        "label.from": "From",
        "label.to": "To",
        "label.member_id": "Member ID",
        "label.is_paid": "Is Paid",
        "label.total_records": "Total records",
        "label.total_principal": "Total principal",
        "label.total_paid": "Total paid",
        "label.principal_repaid": "Principal repaid",
        "label.interest_income": "Interest income",
        "label.paid_fines": "Paid fines",
        "label.waived_fines": "Waived fines",
        "label.total_savings": "Total savings",
        "label.total_late_fines": "Total late fines",
        "label.total_closings": "Total closings",
        "label.total_expenses": "Total expenses",
        "label.total_payouts": "Total payouts",
        "label.total_requests": "Total requests",
        "label.pending_requests": "Pending requests",
        "label.requested_amount": "Requested amount",
        "label.approved_amount": "Approved amount",
        "label.employee": "Employee",
        "label.department": "Department",
        "label.national_id": "National ID",
        "label.account_number": "Account Number",
        "label.reference": "Reference",
        "label.balance": "Balance",
        "label.opening_balance": "Opening Balance",
        "label.closing_balance": "Closing Balance",
        "label.statement_period": "Statement Period",
        "label.payment_status": "Payment Status",
        "label.approved_loan": "Approved Loan",
        "label.authorized_by": "Authorized By",
        "label.approved_on": "Approved On",
        "label.issued_date": "Issued On",
        "label.joined_date": "Joined On",
        "label.year_savings": "Year Savings",
        "label.year_profit": "Year Profit",
        "label.lifetime_savings": "Lifetime Savings",
        "label.lifetime_profit": "Lifetime Profit",
        "label.lifetime_total": "Lifetime Total",
        "value.member": "Member",
        "value.client": "Client",
        "value.paid": "Paid",
        "value.unpaid": "Unpaid",
        "value.ongoing": "Ongoing",
        "value.defaulted": "Defaulted",
        "value.pending": "Pending",
        "value.approved": "Approved",
        "value.rejected": "Rejected",
        "value.waived": "Waived",
        "value.late": "Late",
        "value.on_time": "On time",
        "value.overdue": "Overdue",
        "value.near_due": "Near due",
        "value.committee_review_required": "Committee review required",
        "value.all_profits": "All Profits",
        "value.partial_profit": "Partial Profit",
        "value.self_requested": "Self Requested",
        "value.requested_on_behalf": "Requested On Behalf",
        "value.direct_entry": "Direct Entry",
        "value.fine_type_saving": "Late Saving",
        "value.fine_type_loan": "Late Loan",
        "value.fine_type_admin": "Administrative",
        "value.fine_type_other": "Other",
        "value.transaction_saving": "Saving",
        "value.transaction_loan": "Loan",
        "value.transaction_repayment": "Loan Repayment",
        "value.transaction_fine": "Fine",
        "value.transaction_expense": "Expense",
        "value.transaction_membership": "Membership Fee",
        "value.transaction_system": "System",
        "value.action_create": "Create",
        "value.action_update": "Update",
        "value.action_delete": "Delete",
        "value.action_pay": "Pay",
        "value.role_admin": "Admin",
        "value.role_manager": "Manager",
        "value.role_member": "Member",
        "value.role_teller": "Teller",
        "value.role_loan_officer": "Loan Officer",
        "value.role_finance": "Finance Officer",
        "value.role_auditor": "Auditor",
        "value.role_client": "Client",
        "value.role_staff": "Staff",
        "value.all_time": "All time",
    },
    "fr": {
        "company.name": "IKIMINA REHOBOTH",
        "company.subtitle": "Rapport du systeme de gestion",
        "company.location": "Kigali - Rwanda",
        "company.registration": "Reg. No 1213-T-00009",
        "company.address": "Remera sector- Gasabo District",
        "company.email_line": "email: ikiminarehoboth@gmail.com",
        "company.phone_line": "Tel: +250788305423 / +250788551596",
        "company.bank_line": "BK ACC NO: 0004 2069 5448 375",
        "meta.generated_by": "Genere par",
        "meta.generated_at": "Genere le",
        "meta.page": "Page",
        "meta.signature": "Signature",
        "meta.name": "Nom",
        "meta.title": "Fonction",
        "meta.date": "Date",
        "meta.contact": "Contact",
        "meta.email": "Email",
        "report.loans.title": "Rapport des prets",
        "report.loans.subtitle": "Prets par beneficiaire, type, montant et statut",
        "report.loan_repayments.title": "Rapport des remboursements de prets",
        "report.loan_repayments.subtitle": "Historique des remboursements avec ventilation principal/interets",
        "report.fines.title": "Rapport des amendes",
        "report.fines.subtitle": "Amendes par membre, regle, montant et statut",
        "report.monthly_savings.title": "Rapport de l'epargne mensuelle",
        "report.monthly_savings.subtitle": "Rapport des collectes d'epargne avec amendes et statut de paiement",
        "report.member_savings_statement.title": "Releve d'epargne du membre",
        "report.member_savings_statement.subtitle": "Historique de vos depots d'epargne avec solde progressif du compte",
        "report.annual_closing.title": "Rapport de cloture annuelle",
        "report.annual_closing.subtitle": "Resume de la cloture financiere par annee",
        "report.profit_payouts.title": "Rapport des paiements de benefices",
        "report.profit_payouts.subtitle": "Paiements de benefices des membres enregistres",
        "report.profit_requests.title": "Rapport des demandes de benefices",
        "report.profit_requests.subtitle": "Demandes de benefices des membres et statut d'examen",
        "report.transaction_logs.title": "Rapport des journaux d'operations",
        "report.transaction_logs.subtitle": "Rapport d'audit operationnel filtre",
        "report.income.title": "Rapport des revenus",
        "report.income.subtitle": "Revenus enregistres dans le systeme",
        "report.expenses.title": "Rapport des depenses",
        "report.expenses.subtitle": "Depenses et decaissements enregistres",
        "report.membership_fees.title": "Rapport des frais d'adhesion",
        "report.membership_fees.subtitle": "Paiements des frais d'adhesion enregistres",
        "report.salary_payments.title": "Rapport des salaires",
        "report.salary_payments.subtitle": "Paiements de salaires enregistres",
        "report.loan_requests.title": "Rapport des demandes de pret",
        "report.loan_requests.subtitle": "Demandes de pret soumises et decisions",
        "report.member_certificate.title": "Certificat de membre",
        "report.member_certificate.subtitle": "Certificat d'adhesion approuve",
        "label.id": "ID",
        "label.owner": "Beneficiaire",
        "label.owner_type": "Type de beneficiaire",
        "label.loan_type": "Type de pret",
        "label.principal": "Principal",
        "label.total_amount": "Montant total",
        "label.remaining": "Restant",
        "label.remaining_balance": "Solde restant",
        "label.status": "Statut",
        "label.due_date": "Date limite",
        "label.loan_id": "ID pret",
        "label.member": "Membre",
        "label.rule": "Regle",
        "label.type": "Type",
        "label.amount": "Montant",
        "label.interest": "Interets",
        "label.calculated_on": "Calcule le",
        "label.category": "Categorie",
        "label.month": "Mois",
        "label.year": "Annee",
        "label.saved_on": "Enregistre le",
        "label.received_by": "Recu par",
        "label.late_fine": "Amende de retard",
        "label.savings": "Epargne",
        "label.total_adjusted_capital": "Capital ajuste total",
        "label.profit_rate": "Taux de benefice",
        "label.loan_interest": "Interets de pret",
        "label.fines": "Amendes",
        "label.expenses": "Depenses",
        "label.net_profit": "Benefice net",
        "label.closed_by": "Cloture par",
        "label.closed_on": "Cloture le",
        "label.paid_on": "Paye le",
        "label.recorded_by": "Enregistre par",
        "label.notes": "Notes",
        "label.requested_by": "Demande par",
        "label.mode": "Mode",
        "label.requested": "Demande",
        "label.approved": "Approuve",
        "label.requested_on": "Demande le",
        "label.reviewed_by": "Examine par",
        "label.time": "Heure",
        "label.user": "Utilisateur",
        "label.action": "Action",
        "label.model": "Model",
        "label.object_id": "ID objet",
        "label.details": "Details",
        "label.value": "Valeur",
        "label.ip_address": "Adresse IP",
        "label.search": "Recherche",
        "label.status_group": "Groupe de statut",
        "label.owner_id": "ID beneficiaire",
        "label.loan_status": "Statut du pret",
        "label.due_from": "Date limite debut",
        "label.due_to": "Date limite fin",
        "label.from": "De",
        "label.to": "A",
        "label.member_id": "ID membre",
        "label.is_paid": "Est paye",
        "label.total_records": "Total des enregistrements",
        "label.total_principal": "Total du principal",
        "label.total_paid": "Total paye",
        "label.principal_repaid": "Principal rembourse",
        "label.interest_income": "Revenus d'interets",
        "label.paid_fines": "Amendes payees",
        "label.waived_fines": "Amendes annulees",
        "label.total_savings": "Epargne totale",
        "label.total_late_fines": "Total des amendes de retard",
        "label.total_closings": "Total des clotures",
        "label.total_expenses": "Depenses totales",
        "label.total_payouts": "Total des paiements",
        "label.total_requests": "Total des demandes",
        "label.pending_requests": "Demandes en attente",
        "label.requested_amount": "Montant demande",
        "label.approved_amount": "Montant approuve",
        "label.employee": "Employe",
        "label.department": "Departement",
        "label.national_id": "Numero d'identite",
        "label.account_number": "Numero de compte",
        "label.reference": "Reference",
        "label.balance": "Solde",
        "label.opening_balance": "Solde initial",
        "label.closing_balance": "Solde final",
        "label.statement_period": "Periode du releve",
        "label.payment_status": "Statut du paiement",
        "label.approved_loan": "Pret approuve",
        "label.authorized_by": "Autorise par",
        "label.approved_on": "Approuve le",
        "label.issued_date": "Emis le",
        "label.joined_date": "Date d'adhesion",
        "label.year_savings": "Epargne annuelle",
        "label.year_profit": "Benefice annuel",
        "label.lifetime_savings": "Epargne cumulee",
        "label.lifetime_profit": "Benefice cumule",
        "label.lifetime_total": "Total cumule",
        "value.member": "Membre",
        "value.client": "Client",
        "value.paid": "Paye",
        "value.unpaid": "Non paye",
        "value.ongoing": "En cours",
        "value.defaulted": "En defaut",
        "value.pending": "En attente",
        "value.approved": "Approuve",
        "value.rejected": "Rejete",
        "value.waived": "Annule",
        "value.late": "En retard",
        "value.on_time": "A temps",
        "value.overdue": "En retard",
        "value.near_due": "Proche de l'echeance",
        "value.committee_review_required": "Examen du comite requis",
        "value.all_profits": "Tous les benefices",
        "value.partial_profit": "Benefice partiel",
        "value.self_requested": "Auto-demande",
        "value.requested_on_behalf": "Demande pour autrui",
        "value.direct_entry": "Saisie directe",
        "value.fine_type_saving": "Epargne en retard",
        "value.fine_type_loan": "Pret en retard",
        "value.fine_type_admin": "Administratif",
        "value.fine_type_other": "Autre",
        "value.transaction_saving": "Epargne",
        "value.transaction_loan": "Pret",
        "value.transaction_repayment": "Remboursement",
        "value.transaction_fine": "Amende",
        "value.transaction_expense": "Depense",
        "value.transaction_membership": "Frais d'adhesion",
        "value.transaction_system": "Systeme",
        "value.action_create": "Creation",
        "value.action_update": "Mise a jour",
        "value.action_delete": "Suppression",
        "value.action_pay": "Paiement",
        "value.role_admin": "Admin",
        "value.role_manager": "Manager",
        "value.role_member": "Membre",
        "value.role_teller": "Caissier",
        "value.role_loan_officer": "Agent de pret",
        "value.role_finance": "Agent financier",
        "value.role_auditor": "Auditeur",
        "value.role_client": "Client",
        "value.role_staff": "Personnel",
        "value.all_time": "Toute la periode",
    },
}


REPORT_ENUMS = {
    "owner_type": {
        "MEMBER": "value.member",
        "CLIENT": "value.client",
    },
    "loan_status": {
        "ONGOING": "value.ongoing",
        "PAID": "value.paid",
        "DEFAULTED": "value.defaulted",
    },
    "status_group": {
        "PAID": "value.paid",
        "UNPAID": "value.unpaid",
        "OVERDUE": "value.overdue",
        "NEAR_DUE": "value.near_due",
    },
    "request_mode": {
        "ALL": "value.all_profits",
        "PARTIAL": "value.partial_profit",
    },
    "request_status": {
        "PENDING": "value.pending",
        "APPROVED": "value.approved",
        "REJECTED": "value.rejected",
    },
    "request_origin": {
        "SELF": "value.self_requested",
        "ON_BEHALF": "value.requested_on_behalf",
        "DIRECT": "value.direct_entry",
    },
    "fine_type": {
        "SAVING": "value.fine_type_saving",
        "LOAN": "value.fine_type_loan",
        "ADMIN": "value.fine_type_admin",
        "OTHER": "value.fine_type_other",
    },
    "fine_status": {
        "PAID": "value.paid",
        "PENDING": "value.pending",
        "WAIVED": "value.waived",
    },
    "saving_status": {
        "ON_TIME": "value.on_time",
        "LATE": "value.late",
        "COMMITTEE_REVIEW_REQUIRED": "value.committee_review_required",
    },
    "transaction_type": {
        "SAVING": "value.transaction_saving",
        "LOAN": "value.transaction_loan",
        "REPAYMENT": "value.transaction_repayment",
        "FINE": "value.transaction_fine",
        "EXPENSE": "value.transaction_expense",
        "MEMBERSHIP": "value.transaction_membership",
        "SYSTEM": "value.transaction_system",
    },
    "transaction_action": {
        "CREATE": "value.action_create",
        "UPDATE": "value.action_update",
        "DELETE": "value.action_delete",
        "PAY": "value.action_pay",
    },
    "user_role": {
        "ADMIN": "value.role_admin",
        "MANAGER": "value.role_manager",
        "MEMBER": "value.role_member",
        "TELLER": "value.role_teller",
        "LOAN_OFFICER": "value.role_loan_officer",
        "FINANCE": "value.role_finance",
        "AUDITOR": "value.role_auditor",
        "CLIENT": "value.role_client",
        "STAFF": "value.role_staff",
    },
}


def normalize_report_lang(lang):
    value = str(lang or "").strip().lower()
    if not value:
        return "en"

    value = value.split(",")[0].split(";")[0].strip()
    if value.startswith("rw"):
        return "rw"
    if value.startswith("fr"):
        return "fr"
    return "en"


def get_report_lang(request, default="en"):
    query_value = ""
    if hasattr(request, "query_params"):
        query_value = request.query_params.get("lang", "")

    header_value = ""
    if hasattr(request, "headers"):
        header_value = request.headers.get("Accept-Language", "")
    if not header_value and hasattr(request, "META"):
        header_value = request.META.get("HTTP_ACCEPT_LANGUAGE", "")

    return normalize_report_lang(query_value or header_value or default)


def report_text(lang, key, default=None, **kwargs):
    normalized = normalize_report_lang(lang)
    dictionary = REPORT_TEXT.get(normalized, REPORT_TEXT["en"])
    text = dictionary.get(key) or REPORT_TEXT["en"].get(key) or default or key
    if kwargs:
        return text.format(**kwargs)
    return text


def report_choice(lang, group, value, default=None):
    normalized_value = str(value or "").strip().upper()
    if not normalized_value:
        return default if default not in (None, "") else ""

    key = REPORT_ENUMS.get(group, {}).get(normalized_value)
    if not key:
        return default if default is not None else str(value)
    return report_text(lang, key, default=str(value))


def report_user_name(user):
    if not user:
        return ""

    full_name = ""
    if hasattr(user, "get_full_name"):
        full_name = (user.get_full_name() or "").strip()
    if full_name:
        return full_name

    holder_name = str(getattr(user, "holder_name", "") or "").strip()
    if holder_name:
        return holder_name

    display_name = str(getattr(user, "display_name", "") or "").strip()
    if display_name:
        return display_name

    username = str(getattr(user, "username", "") or "").strip()
    if username:
        return username

    return str(user)


def report_user_title(lang, user, default=None):
    if not user:
        return default or ""

    role = str(getattr(user, "role", "") or "").strip().upper()
    if not role and getattr(user, "is_staff", False):
        role = "STAFF"

    fallback = default if default is not None else role.replace("_", " ").title()
    return report_choice(lang, "user_role", role, default=fallback)
